export {
  approveUser,
  blockUser,
  expireLicense,
  extendLicense,
  fetchCurrentSession,
  getAuthErrorMessage,
  getLoginErrorMessage,
  getPostLoginRoute,
  getRegisterErrorMessage,
  grantBetaLicense,
  isUserAllowedToUseApp,
  getLicenseBlockReason,
  listUsersForAdmin,
  signInWithPassword,
  signOutUser,
  signUpUser,
  type AuthPayload,
  type AuthResult,
  type RegisterResult,
} from './supabaseAuthService';
