export {
  approveUser,
  blockUser,
  clearPasswordRecoveryPending,
  expireLicense,
  extendLicense,
  fetchCurrentSession,
  getAuthErrorMessage,
  getLoginErrorKey,
  getLoginErrorMessage,
  getPostLoginRoute,
  getRegisterErrorKey,
  getRegisterErrorMessage,
  grantBetaLicense,
  hasPasswordRecoverySession,
  isUserAllowedToUseApp,
  getLicenseBlockReason,
  listUsersForAdmin,
  markPasswordRecoveryPending,
  MIN_PASSWORD_LENGTH,
  PASSWORD_RECOVERY_FLAG_KEY,
  readPasswordRecoveryPendingFlag,
  requestPasswordReset,
  signInWithPassword,
  signOutUser,
  signUpUser,
  updatePasswordDuringRecovery,
  type AuthPayload,
  type AuthResult,
  type PasswordResetRequestError,
  type PasswordUpdateError,
  type RegisterResult,
} from './supabaseAuthService';
